# 2.0 基本技能
    - 线性代数：机器学习通常需要处理大型数据集。线性代数为人们提供了一些用来处理表格数据的方法。
    - 微积分知识：深度学习是关于优化的学习。对于一个带有参数的模型，我们想要找到其中能拟合数据的最好模型。在算法的每个步骤中，决定以何种方式调整参数需要一点微积分知识。
    - 概率论：机器学习还涉及如何做出预测：给定观察到的信息，某些未知属性可能的值是多少？要在不确定的情况下进行严格的推断，我们需要借用概率语言

本章会快速介绍一些基本且常用的数学知识，以便读者能够理解书中的大部分数学内容。如果读者想要深入理解全部数学内容，可以进一步学习本书数学附录中给出的数学基础知识。

## 2.1 数据操作
    - n维数组，也称为张量（tensor）。张量表示一个由数值组成的数组，这个数组可能有多个维度。具有一个轴的张量对应数学上的向量（vector）；具有两个轴的张量对应数学上的矩阵（matrix）；具有两个轴以上的张量没有特殊的数学名称。
    - 深度学习框架中的Tensor比Numpy的ndarray多一些重要功能：首先，GPU很好地支持加速计算，而NumPy仅支持CPU计算；其次，张量类支持自动微分。这些功能使得张量类更适合深度学习。

In [2]:
import torch
x = torch.arange(66)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [2]:
x.shape #沿每个轴的长度

torch.Size([66])

In [3]:
x.numel() #获得张量中元素的总数

66

In [9]:
x.reshape(3,22) #(高度，宽度)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
         40, 41, 42, 43],
        [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
         62, 63, 64, 65]])

In [5]:
y = torch.arange(12)

In [6]:
y

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
y.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
y.reshape(-1,2)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [10]:
x.reshape(-1, 2) #-1 是调用自动计算出维度的功能

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59],
        [60, 61],
        [62, 63],
        [64, 65]])

In [13]:
z = torch.zeros(2,3,4) #zeros
z

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
z = torch.ones(2, 3, 4, device='cuda')  # 示例张量
z

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]], device='cuda:0')

In [16]:
torch.randn(3, 4)

tensor([[-0.3852, -0.0298,  0.6126, -1.3536],
        [ 0.8953,  0.8564, -0.9042, -0.8657],
        [-1.0654, -0.1310,  0.2560,  1.6196]])

In [17]:
a = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [18]:
a.shape

torch.Size([3, 4])

### 2.1.1 高维tensor的理解
- torch.ones(2, 3, 4) 创建的是一个三维张量,这里的 2 表示最外层维度的大小，可以把它理解为"有 2 个 3×4 的矩阵摞在一起"。数括号层数也能看出来:三层 [[[,就是三维。
- 直观理解（2，3，4）：2 个块 → 每块 3 行 → 每行 4 个元素
- 张量的每个维度本身没有语义,它们只是 axis 0、axis 1、axis 2,含义完全取决于你的数据是什么。
- 最常见的解读是 batch size:一次喂给模型 2 个样本,每个样本是一个 3×4 的矩阵。比如 NLP 里 (batch=2, seq_len=3, embed_dim=4) 就是 2 个句子、每句 3 个 token、每个 token 用 4 维向量表示。
- 图像场景下 (C, H, W) ,最外层的数则是通道数,比如 (3, 224, 224) 是 RGB 三通道。加上 batch 就是四维 (N, C, H, W)。
- 高维张量不要试图在脑子里"画出来"——三维以上就画不动了。正确的方法是递归地读 shape:不管多少维,永远只读最外层,把剩下的当作一个整体。
  
    核心心法:N 个 X
    - (2, 3, 4)        = 2 个 (3, 4) 矩阵
    - (5, 2, 3, 4)     = 5 个 (2, 3, 4) 张量
    - (6, 5, 2, 3, 4)  = 6 个 (5, 2, 3, 4) 张量

- 工程中真正遇到的高维张量,每个维度都有明确含义,记语义比记形状有用得多:  
    1. 图像 batch:4 维  
        (N, C, H, W) = (32, 3, 224, 224)  
        即 32 张图,每张 3 通道,每通道 224×224  

    2. 视频 batch:5 维  
        (N, T, C, H, W) = (8, 16, 3, 224, 224)  
        即 8 段视频,每段 16 帧,每帧是一张 3 通道图  

    3. Transformer 中的 attention:4 维  
        (batch, num_heads, seq_len, head_dim) = (2, 8, 512, 64)  
        即 2 个句子,8 个注意力头,每头处理 512 个 token,每个 token 64 维
 
- 索引就是"剥一层"，每索引一次,最外层维度消失:
    ```
    pythonx = torch.ones(5, 2, 3, 4)
  
    x[0].shape       # (2, 3, 4)  → 取出第 1 个三维块
    x[0, 1].shape    # (3, 4)     → 再取出里面第 2 个矩阵
    x[0, 1, 2].shape # (4,)       → 再取出第 3 行
    x[0, 1, 2, 3]    # 标量        → 具体某个数

    ```
  
    反过来,`sum(axis=k)`、`mean(axis=k)` 是"消掉第 k 维",`unsqueeze(k)` 是"在第 k 个位置插一个大小为 1 的维"。所有 shape 操作都是在这套嵌套结构上增删层。

### 2.1.2 理解测试
1. x.shape          # torch.Size([2, 3, 4])
2. x.sum(axis=0)    # 沿第 0 维求和 → shape 变成 (3, 4),两个矩阵对应位置相加 （axis 复数axes或axis或axises）
3. x.sum(axis=2)    # 沿最后一维求和 → shape 变成 (2, 3),每行 4 个数加成 1 个
4. x.reshape(3, 8)  # 元素总数 24 不变,只是重新排列

记住一个规律:sum(axis=k) 就是把第 k 个维度"消掉",其余维度保留。这个直觉在后续写训练循环、算 loss 时会反复用到。 

### 2.1.3 “维” 的区分
* 第一种:张量的维度(阶数),对应 ndim  
指的是"有几层嵌套"、"需要几个下标才能定位一个元素":  

```
x = torch.tensor([1, 2, 3, 4, 5, 6])  
x.ndim    # 1  → 一维张量,一个下标 x[i] 就能定位  
x.shape   # torch.Size([6])  
```
按这个意义,[1,2,3,4,5,6] 是一维的,数括号层数就是数这个。英文叫 dimension / rank / number of axes。  

* 第二种:向量空间的维数,对应长度  
线性代数里说"6 维向量",指的是这个向量有 6 个分量,活在一个 6 维空间 ℝ⁶ 里——你需要 6 个数才能描述这个点。
英文叫 dimensionality,比如 "a 6-dimensional vector"。

视角|说法|数的是什么
----|----|----------
张量/编程视角|一维张量|括号层数 / 下标个数  
线性代数视角|6 维向量|分量个数 / 空间维数  

两种说法都对,不矛盾,只是"维"字指向不同的东西。  
怎么在实际语境中区分呢？  

一个简单的判断法:说"X 维张量/X 维数组"时,几乎总是指 ndim;说"X 维向量/X 维空间/X 维特征"时,几乎总是指分量个数。  
深度学习里两种用法会同时出现,比如这句话完全合法:  

> "embedding 层的输出是一个二维张量,shape 为 (512, 768),表示 512 个 token,每个 token 是一个 768 维向量。"  

前一个"二维"数的是张量的轴,后一个"768 维"数的是向量的分量。  
所以有时我们会发现英文文献里也经常用 "axis" 或 "rank" 来称呼第一种,专门避开 dimension 这个词,就是为了绕开这个歧义。  

顺带一提,这也解释了为什么 PyTorch 里 sum(axis=0) 用的词是 axis(轴)而不是 dimension——沿着某根"轴"操作,比"沿着某个维度"表意更精确。  
不过 PyTorch 同时也接受 dim=0 这个参数名,所以两套叫法你都会见到。

## 2.2 运算符

### 2.2.1 按元素（elementwise）运算：将标准标量运算符应用于数组的每个元素

- 在数学表示法中，我们将通过符号f : R → R 来表示一元标量运算符（只接收一个输入）。

- 我们通过符号f : R,R → R 表示二元标量运算符，这意味着该函数接收两个输入，并产生一个输出。

- 给定同一形状的任意两个向量u和v和二元运算符f，我们可以得到向量c = F(u, v)。具体计算方法是：

$$c_i \leftarrow f(u_i,v_i)$$
> 其中$c_i$、$u_i$和$v_i$分别是向量c、u和v中的元素。在这里，我们通过将标量函数升级为按元素向量运算来生成向量值F : $R_d$,$R_d$ $\rightarrow$ $R_d$。  
> 对于任意具有相同形状的张量， 常见的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算。

In [20]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [18]:
torch.exp(x) #用于计算输入张量 x 中每个元素的自然指数函数值（即以自然常数 e ≈ 2.71828 为底的指数函数）

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

### 2.2.2 把多个张量连结（concatenate）在一起， 把它们端对端地叠起来形成一个更大的张量

In [21]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [22]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [27]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [28]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1) # 按第0轴连接（concatenate）； 按第1轴连接

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [29]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [30]:
X.sum()

tensor(66.)

### 2.1.3 广播机制

在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作。  
这种机制的工作方式如下：  

> - 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；   

> - 对生成的数组执行按元素操作。  

在大多数情况下，我们将沿着数组中长度为1的轴进行广播  

**广播只有两条规则**  

- **规则 1:从右往左对齐 shape,逐维比较**  
- **规则 2:每一维上,两数相等,或其中一个是 1,才兼容。是 1 的那维被复制扩展;维数不够的,左边补 1**

例子：

In [32]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

由于a和b分别是3 * 2和 1 * 2 矩阵，如果让它们相加，它们的形状不匹配。   
我们将两个矩阵广播为一个更大的矩阵，  
如下所示：矩阵a将复制列， 矩阵b将复制行，然后再按元素相加。

In [33]:
a+b #广播

tensor([[0, 1],
        [1, 2],
        [2, 3]])

----

**示例：**  

A: (3, 4)  
B:    (4,)  
右对齐:B 补成 (1, 4)。逐维比:4==4 ✓,3 vs 1 → B 沿第 0 维复制 3 份。结果 (3, 4)。  

pythonA: (2, 3, 4)  
B:    (3, 1)  
B 补成 (1, 3, 1)。比:4 vs 1 ✓,3==3 ✓,2 vs 1 ✓。结果 (2, 3, 4)。  

pythonA: (3, 4)  
B: (4, 3)  
4 vs 3,既不相等也没有 1。报错。不要指望它"智能地转置"。  

**经典陷阱,现在就记住：**  
a = torch.ones(3)      # (3,)  
b = torch.ones(3, 1)   # (3, 1)  
(a + b).shape          # ?  
想清楚再往下看。  
右对齐:(1, 3) vs (3, 1) → 结果 (3, 3)。  

你以为在做逐元素加法,实际做了外积式的全组合。  
大量线上 bug 源于此:loss 该是标量,算出来是个矩阵,还不报错,静默地给你错误的梯度。  
所以工程里常做 assert pred.shape == target.shape,这不是洁癖,是自保。

为什么它是这么设计的？  
广播是"虚拟复制":X + b 中 (3,4) 加 (4,),语义上等价于把 b 复制 3 行再加,但不分配那块内存。

In [48]:
e = torch.ones(5, 1, 4) + torch.ones(3, 1) 
e.shape

torch.Size([5, 3, 4])

In [49]:
f = torch.ones(2, 1) * torch.ones(1, 2) 
f.shape

torch.Size([2, 2])

In [51]:
# torch.ones(3, 2) + torch.ones(2, 3)  #不可加

In [55]:
f.ndim

2

### 索引和切片
就像在任何其他Python数组中一样，张量中的元素可以通过索引访问。与任何Python数组一样：第一个元素的索引是0，最后一个元素索引是‐1；可以指定范围以包含第一个元素和最后一个之前的元素。

In [ ]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [ ]:
X[1, 2] = 9 #通过指定索引来将元素写入矩阵。
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

如果我们想为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。例如，[0:2, :]访问第1行和第2行，其中“:”代表沿轴1（列）的所有元素。虽然我们讨论的是矩阵的索引，但这也适用于向量和超过2个维度的张量。

In [ ]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 节省内存
用Y = X + Y，我们将取消引用Y指向的张量，而是指向新分配的内存处的张量。

In [ ]:
before = id(Y)
Y = Y + X
id(Y) == before

False

这可能是不可取的，原因有两个：
1. 首先，我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。通常情况下，我们希望原地执行这些更新；
2. 如果我们不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数。

可以使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:]= <expression>

In [ ]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2110924717840
id(Z): 2110924717840

### 转换为其他Python对象

In [ ]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
#要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数。
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

深度学习存储和操作数据的主要接口是张量（n维数组）。

In [ ]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [ ]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

## 数据预处理

In [ ]:
import os
os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [ ]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [ ]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]

In [ ]:
inputs

   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN

In [ ]:
inputs.mean(numeric_only=True)

NumRooms    3.0
dtype: float64

In [ ]:
inputs = inputs.fillna(inputs.mean(numeric_only=True))

In [ ]:
inputs

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [ ]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [ ]:
import torch
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

总结： 

• pandas软件包是Python中常用的数据分析工具中，pandas可以与张量兼容。

• 用pandas处理缺失的数据时，我们可根据情况选择用插值法和删除法。

## 线性代数

请注意，维度（dimension）这个词在不同上下文时往往会有不同的含义，这经常会使人感到困惑。为了清楚起见，我们在此明确一下：向量或轴的维度被用来表示向量或轴的长度，即向量或轴的元素数量。然而，张量的维度用来表示张量具有的轴数。在这个意义上，张量的某个轴的维数就是这个轴的长度。

In [ ]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

大量文献认为列向量是向量的默认方向，在本书中也是如此。

In [ ]:
x[3]

tensor(3)

长度、维度和形状：向量的长度通常称为向量的维度（dimension）。与普通的Python数组一样，我们可以通过调用Python的内置len()函数来访问张量的长度。

In [ ]:
len(x),x.shape

(4, torch.Size([4]))

In [ ]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [ ]:
A.T  #转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

## 张量
就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构。张量（本小节中的“张量”指代数对象）是描述具有任意数量轴的n维数组的通用方法。例如，向量是一阶张量，矩阵是二阶张量。张量用特殊字体的大写字母表示（例如，X、Y和Z），它们的索引机制（例如$x_{ijk}$和$[X]_{1,2i−1,3}$）与矩阵类似。

In [ ]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### Hadamard积
两个矩阵的按元素乘法

In [ ]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B
A, A * B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

### 降维

In [ ]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [ ]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [ ]:
A_sum_axis0 = A.sum(axis=1)
A_sum_axis0, A_sum_axis0.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [ ]:
A.sum(axis=[0, 1]) # 结果和A.sum()相同,沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和。

tensor(190.)